2020-06-11 16:31:46,284 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 16:31:46,295 - octoprint.server - INFO - --- Log roll over detected ---------------------------------------------------
2020-06-11 16:31:46,296 - octoprint.server - INFO - OctoPrint 1.4.0
2020-06-11 16:31:46,301 - octoprint.plugin.core - INFO - 15 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/backup
|  Core Wizard (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  Discovery (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/errortracking
|  Logging (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/logging
|  Login UI (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/loginui
|  Pi Support Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2020-06-11 16:31:46,338 - octoprint.environment - INFO - Detected environment is Python 2.7.16 under Linux (linux2). Details:
|  hardware:
|      cores: 4
|      freq: 1400.0
|      ram: 971055104
|  os:
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 3 Model B Plus Rev 1.3
|  python:
|      pip: 20.1.1
|      version: 2.7.16
|      virtualenv: /home/pi/OctoPrint/venv
2020-06-11 16:31:46,340 - octoprint.server - INFO - ------------------------------------------------------------------------------
2020-06-11 16:46:46,303 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 17:01:46,305 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 17:16:46,309 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 17:31:46,312 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 17:46:46,316 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 18:01:46,319 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 18:16:46,320 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 18:31:46,322 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 18:46:46,324 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 18:48:27,473 - octoprint.startup - INFO - ******************************************************************************
2020-06-11 18:48:27,475 - octoprint.startup - INFO - Starting OctoPrint 1.4.0
2020-06-11 18:48:27,476 - octoprint.startup - INFO - ******************************************************************************
2020-06-11 18:48:29,270 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-06-11 18:48:32,868 - octoprint.plugins.octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2020-06-11 18:48:32,885 - octoprint.plugin.core - INFO - Found 15 plugin(s) providing 15 mixin implementations, 27 hook handlers
2020-06-11 18:48:33,130 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2020-06-11 18:48:33,176 - octoprint.server - INFO - Intermediary server started
2020-06-11 18:48:33,177 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-06-11 18:48:33,279 - octoprint.plugin.core - INFO - Found 15 plugin(s) providing 15 mixin implementations, 27 hook handlers
2020-06-11 18:48:33,310 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2020-06-11 18:48:33,311 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2020-06-11 18:48:33,316 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: u"Need(method='role', value=u'plugin_action_command_prompt_interact')")
2020-06-11 18:48:33,317 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: u"Need(method='role', value=u'plugin_announcements_read')")
2020-06-11 18:48:33,318 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: u"Need(method='role', value=u'plugin_announcements_manage'), Need(method='role', value=u'plugin_announcements_read')")
2020-06-11 18:48:33,320 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: u"Need(method='role', value=u'plugin_appkeys_admin')")
2020-06-11 18:48:33,321 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: u"Need(method='role', value=u'plugin_backup_access')")
2020-06-11 18:48:33,322 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: u"Need(method='role', value=u'plugin_logging_manage')")
2020-06-11 18:48:33,324 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: u"Need(method='role', value=u'plugin_pi_support_check')")
2020-06-11 18:48:33,326 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: u"Need(method='role', value=u'plugin_pluginmanager_manage')")
2020-06-11 18:48:33,327 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: u"Need(method='role', value=u'plugin_pluginmanager_install'), Need(method='role', value=u'plugin_pluginmanager_manage')")
2020-06-11 18:48:33,328 - octoprint.server - INFO - Added new permission from plugin printer_safety_check: PLUGIN_PRINTER_SAFETY_CHECK_DISPLAY (needs: u"Need(method='role', value=u'plugin_printer_safety_check_display')")
2020-06-11 18:48:33,330 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: u"Need(method='role', value=u'plugin_softwareupdate_check')")
2020-06-11 18:48:33,331 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: u"Need(method='role', value=u'plugin_softwareupdate_update')")
2020-06-11 18:48:33,392 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2020-06-11 18:48:34,347 - octoprint.util.pip - INFO - Using "/home/pi/OctoPrint/venv/bin/python2 -m pip" as command to invoke pip
2020-06-11 18:48:35,127 - octoprint.util.pip - INFO - Version of pip is 20.1.1
2020-06-11 18:48:35,129 - octoprint.util.pip - INFO - pip installs to /home/pi/OctoPrint/venv/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-06-11 18:48:35,130 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-06-11 18:48:35,135 - octoprint.plugin.core - INFO - Initialized 15 plugin implementation(s)
2020-06-11 18:48:35,145 - octoprint.plugin.core - INFO - 15 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/backup
|  Core Wizard (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  Discovery (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/errortracking
|  Logging (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/logging
|  Login UI (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/loginui
|  Pi Support Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2020-06-11 18:48:35,160 - octoprint.environment - INFO - Detected environment is Python 2.7.16 under Linux (linux2). Details:
|  hardware:
|      cores: 4
|      freq: 1400.0
|      ram: 971055104
|  os:
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 3 Model B Plus Rev 1.3
|  python:
|      pip: 20.1.1
|      version: 2.7.16
|      virtualenv: /home/pi/OctoPrint/venv
2020-06-11 18:48:35,168 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2020-06-11 18:48:35,170 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2020-06-11 18:48:36,114 - octoprint.server - INFO - Shutting down intermediary server...
2020-06-11 18:48:36,180 - octoprint.server - INFO - Intermediary server shut down
2020-06-11 18:48:36,183 - octoprint.events - INFO - Processing startup event, this is our first event
2020-06-11 18:48:36,184 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2020-06-11 18:48:36,187 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2020-06-11 18:48:36,191 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2020-06-11 18:48:36,193 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2020-06-11 18:48:36,196 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2020-06-11 18:48:36,249 - octoprint.plugins.pi_support - WARNING - This Raspberry Pi is reporting problems that might lead to bad performance or errors caused by overheating or insufficient power.
!!! UNDERVOLTAGE REPORTED !!! Make sure that the power supply and power cable are capable of supplying enough voltage and current to your Pi.
2020-06-11 18:48:36,255 - octoprint.server - INFO - Listening on http://0.0.0.0:5000 and http://[::]:5000
2020-06-11 18:48:36,300 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at https://plugins.octoprint.org/plugins.json: HTTPSConnectionPool(host='plugins.octoprint.org', port=443): Max retries exceeded with url: /plugins.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x721da3b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 988, in _fetch_repository_from_url
    r = requests.get(repository_url, timeout=30)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='plugins.octoprint.org', port=443): Max retries exceeded with url: /plugins.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x721da3b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2020-06-11 18:48:36,308 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from https://octoprint.org/feeds/important.xml
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 384, in _get_channel_data_from_network
    r = requests.get(url, timeout=30)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='octoprint.org', port=443): Max retries exceeded with url: /feeds/important.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x72b4fd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2020-06-11 18:48:36,317 - octoprint.plugins.pluginmanager - ERROR - Could not fetch notices from https://plugins.octoprint.org/notices.json: HTTPSConnectionPool(host='plugins.octoprint.org', port=443): Max retries exceeded with url: /notices.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x721f7490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 1058, in _fetch_notices_from_url
    r = requests.get(notices_url, timeout=30)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='plugins.octoprint.org', port=443): Max retries exceeded with url: /notices.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x721f7490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2020-06-11 18:48:37,070 - octoprint.util.pip - INFO - Using "/home/pi/OctoPrint/venv/bin/python2 -m pip" as command to invoke pip
2020-06-11 18:48:37,071 - octoprint.util.pip - INFO - pip installs to /home/pi/OctoPrint/venv/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-06-11 18:48:37,073 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-06-11 18:48:37,090 - octoprint.plugins.softwareupdate - WARNING - Could not check octoprint for updates due to a network error
2020-06-11 18:48:37,100 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2020-06-11 19:36:41,815 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 19:51:41,832 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 20:06:41,835 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 20:21:41,837 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 20:36:41,840 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 20:51:41,842 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 21:06:41,844 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 21:21:41,845 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 21:36:41,847 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 21:51:41,848 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 22:06:41,850 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-06-11 21:18:43,471 - octoprint.startup - INFO - ******************************************************************************
2020-06-11 21:18:43,475 - octoprint.startup - INFO - Starting OctoPrint 1.4.0
2020-06-11 21:18:43,476 - octoprint.startup - INFO - ******************************************************************************
2020-06-11 21:18:44,961 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-06-11 21:18:47,274 - octoprint.plugins.octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2020-06-11 21:18:47,302 - octoprint.plugin.core - INFO - Found 15 plugin(s) providing 15 mixin implementations, 27 hook handlers
2020-06-11 21:18:47,573 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2020-06-11 21:18:47,627 - octoprint.server - INFO - Intermediary server started
2020-06-11 21:18:47,629 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-06-11 21:18:47,738 - octoprint.plugin.core - INFO - Found 15 plugin(s) providing 15 mixin implementations, 27 hook handlers
2020-06-11 21:18:47,769 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2020-06-11 21:18:47,771 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2020-06-11 21:18:47,775 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: u"Need(method='role', value=u'plugin_action_command_prompt_interact')")
2020-06-11 21:18:47,777 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: u"Need(method='role', value=u'plugin_announcements_read')")
2020-06-11 21:18:47,779 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: u"Need(method='role', value=u'plugin_announcements_manage'), Need(method='role', value=u'plugin_announcements_read')")
2020-06-11 21:18:47,781 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: u"Need(method='role', value=u'plugin_appkeys_admin')")
2020-06-11 21:18:47,782 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: u"Need(method='role', value=u'plugin_backup_access')")
2020-06-11 21:18:47,783 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: u"Need(method='role', value=u'plugin_logging_manage')")
2020-06-11 21:18:47,785 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: u"Need(method='role', value=u'plugin_pi_support_check')")
2020-06-11 21:18:47,787 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: u"Need(method='role', value=u'plugin_pluginmanager_manage')")
2020-06-11 21:18:47,788 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: u"Need(method='role', value=u'plugin_pluginmanager_install'), Need(method='role', value=u'plugin_pluginmanager_manage')")
2020-06-11 21:18:47,790 - octoprint.server - INFO - Added new permission from plugin printer_safety_check: PLUGIN_PRINTER_SAFETY_CHECK_DISPLAY (needs: u"Need(method='role', value=u'plugin_printer_safety_check_display')")
2020-06-11 21:18:47,791 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: u"Need(method='role', value=u'plugin_softwareupdate_check')")
2020-06-11 21:18:47,793 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: u"Need(method='role', value=u'plugin_softwareupdate_update')")
2020-06-11 21:18:47,845 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2020-06-11 21:18:48,873 - octoprint.util.pip - INFO - Using "/home/pi/OctoPrint/venv/bin/python2 -m pip" as command to invoke pip
2020-06-11 21:18:49,674 - octoprint.util.pip - INFO - Version of pip is 20.1.1
2020-06-11 21:18:49,677 - octoprint.util.pip - INFO - pip installs to /home/pi/OctoPrint/venv/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-06-11 21:18:49,678 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-06-11 21:18:49,682 - octoprint.plugin.core - INFO - Initialized 15 plugin implementation(s)
2020-06-11 21:18:49,692 - octoprint.plugin.core - INFO - 15 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/backup
|  Core Wizard (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  Discovery (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/errortracking
|  Logging (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/logging
|  Login UI (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/loginui
|  Pi Support Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2020-06-11 21:18:49,708 - octoprint.environment - INFO - Detected environment is Python 2.7.16 under Linux (linux2). Details:
|  hardware:
|      cores: 4
|      freq: 1400.0
|      ram: 971055104
|  os:
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 3 Model B Plus Rev 1.3
|  python:
|      pip: 20.1.1
|      version: 2.7.16
|      virtualenv: /home/pi/OctoPrint/venv
2020-06-11 21:18:49,716 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2020-06-11 21:18:49,718 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2020-06-11 21:18:50,667 - octoprint.server - INFO - Shutting down intermediary server...
2020-06-11 21:18:50,757 - octoprint.server - INFO - Intermediary server shut down
2020-06-11 21:18:50,760 - octoprint.events - INFO - Processing startup event, this is our first event
2020-06-11 21:18:50,761 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2020-06-11 21:18:50,764 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2020-06-11 21:18:50,768 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2020-06-11 21:18:50,769 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2020-06-11 21:18:50,772 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2020-06-11 21:18:50,784 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on xenovia for SSDP
2020-06-11 21:18:50,825 - octoprint.plugins.pi_support - WARNING - This Raspberry Pi is reporting problems that might lead to bad performance or errors caused by overheating or insufficient power.
!!! UNDERVOLTAGE REPORTED !!! Make sure that the power supply and power cable are capable of supplying enough voltage and current to your Pi.
2020-06-11 21:18:50,831 - octoprint.server - INFO - Listening on http://0.0.0.0:5000 and http://[::]:5000
2020-06-11 21:18:51,643 - octoprint.util.pip - INFO - Using "/home/pi/OctoPrint/venv/bin/python2 -m pip" as command to invoke pip
2020-06-11 21:18:51,645 - octoprint.util.pip - INFO - pip installs to /home/pi/OctoPrint/venv/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-06-11 21:18:51,645 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-06-11 21:18:51,767 - octoprint.plugins.announcements - INFO - Loaded channel _important from https://octoprint.org/feeds/important.xml in 0.89s
2020-06-11 21:18:51,988 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from https://plugins.octoprint.org/plugins.json
2020-06-11 21:18:53,840 - octoprint.plugins.pluginmanager - INFO - Loaded plugin notices data from https://plugins.octoprint.org/notices.json
